package com.itelasoft.pso.beans;

import java.util.List;

import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import org.hibernate.annotations.Cascade;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : PSO
//  @ Author : Tharindu
//
//
@Entity
@Table(name = "fundingsources")
public class FundingSource extends BaseEntity {
	private Long id;
	private String fundingCode;
	private String fundingDescription;
	private String fundingType;
	private List<Outlet> outlets;
	private String status;

	public void setId(Long id) {
		this.id = id;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	public Long getId() {
		return id;
	}

	public String getFundingDescription() {
		return fundingDescription;
	}

	public void setFundingDescription(String fundingDescription) {
		this.fundingDescription = fundingDescription;
	}

	public String getFundingType() {
		return fundingType;
	}

	public void setFundingType(String fundingType) {
		this.fundingType = fundingType;
	}

	public void setOutlets(List<Outlet> outlets) {
		this.outlets = outlets;
	}

	@OneToMany(mappedBy = "fundingSource")
	@Cascade(value = { org.hibernate.annotations.CascadeType.DELETE_ORPHAN,
			org.hibernate.annotations.CascadeType.SAVE_UPDATE })
	public List<Outlet> getOutlets() {
		return outlets;
	}

	public void setFundingCode(String fundingCode) {
		this.fundingCode = fundingCode;
	}

	public String getFundingCode() {
		return fundingCode;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	public String getStatus() {
		return status;
	}

}
