package com.itelasoft.pso.beans;

import java.util.Date;
import java.util.List;

import javax.persistence.CascadeType;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.OneToOne;
import javax.persistence.Table;

import org.hibernate.annotations.Fetch;
import org.hibernate.annotations.FetchMode;
import org.hibernate.search.annotations.Analyze;
import org.hibernate.search.annotations.Field;
import org.hibernate.search.annotations.Index;
import org.hibernate.search.annotations.Indexed;
import org.hibernate.search.annotations.IndexedEmbedded;
import org.hibernate.search.annotations.Store;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : pso
//  @ Author : Tharindu
//
//

@Entity
@Indexed
@Table(name = "programs")
public class Program extends BaseEntity {
	private Long id;
	@Field(index = Index.YES, analyze = Analyze.YES, store = Store.NO)
	private String name;
	private Date startDate;
	private Date endDate;
	private ProgramType type;
	@IndexedEmbedded
	private StaffMember coordinator;
	private List<StudentGroup> studentGroups;
	private List<ProgramEvent> programEvents;
	//private double chargeAmount;
	@Field(index = Index.YES, analyze = Analyze.YES, store = Store.NO)
	private String status;
	@IndexedEmbedded
	private Vehicle vehicle;

	// private String rectype;
	// private List<WeekDay> days;

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	public Long getId() {
		return id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Date getStartDate() {
		return startDate;
	}

	public void setStartDate(Date startDate) {
		this.startDate = startDate;
	}

	public Date getEndDate() {
		return endDate;
	}

	public void setEndDate(Date endDate) {
		this.endDate = endDate;
	}

	@ManyToOne
	@JoinColumn(name = "programTypeId")
	@Fetch(FetchMode.JOIN)
	public ProgramType getType() {
		return type;
	}

	public void setType(ProgramType type) {
		this.type = type;
	}

	@ManyToOne
	@JoinColumn(name = "coordinatorId")
	public StaffMember getCoordinator() {
		return coordinator;
	}

	public void setCoordinator(StaffMember coordinator) {
		this.coordinator = coordinator;
	}

	public String getStatus() {
		return status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	/*public void setChargeAmount(double chargeAmount) {
		this.chargeAmount = chargeAmount;
	}

	public double getChargeAmount() {
		return chargeAmount;
	}*/

	public void setVehicle(Vehicle vehicle) {
		this.vehicle = vehicle;
	}

	@OneToOne
	@JoinColumn(name = "vehicleId")
	public Vehicle getVehicle() {
		return vehicle;
	}

	/*
	 * public void setRectype(String rectype) { this.rectype = rectype; }
	 * 
	 * public String getRectype() { return rectype; }
	 * 
	 * public void setDays(List<WeekDay> days) { this.days = days; }
	 * 
	 * @ManyToMany(cascade = CascadeType.PERSIST)
	 * 
	 * @LazyCollection(value = LazyCollectionOption.FALSE)
	 * 
	 * @JoinTable(name = "ProgramWeekXRef", joinColumns = @JoinColumn(name =
	 * "programId"), inverseJoinColumns = @JoinColumn(name = "weekId")) public
	 * List<WeekDay> getDays() { return days; }
	 */

	public void setStudentGroups(List<StudentGroup> studentGroups) {
		this.studentGroups = studentGroups;
	}

	@OneToMany(mappedBy = "program", cascade = CascadeType.ALL)
	public List<StudentGroup> getStudentGroups() {
		return studentGroups;
	}

	public void setProgramEvents(List<ProgramEvent> programEvents) {
		this.programEvents = programEvents;
	}

	@OneToMany(mappedBy = "program")
	public List<ProgramEvent> getProgramEvents() {
		return programEvents;
	}
}
