package com.itelasoft.pso.beans;

import java.util.Date;

import javax.persistence.CascadeType;
import javax.persistence.Entity;
import javax.persistence.EnumType;
import javax.persistence.Enumerated;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.OneToOne;
import javax.persistence.Table;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : pso
//  @ Author : Tharindu
//
//

@Entity
@Table(name = "filedata")
public class FileData {
	private Long id;
	private Long staffId;
	private Long studentId;
	private Long sNeedId;
	private Long vehicleId;
	private Long refId;
	private String fileName;
	private String contentType;
	private EnumFileType fileType;
	private Date dateCreated;
	private BlobFileData blobFileData;

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	public Long getId() {
		return id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public Long getStaffId() {
		return staffId;
	}

	public void setStaffId(Long staffId) {
		this.staffId = staffId;
	}

	public Long getStudentId() {
		return studentId;
	}

	public void setStudentId(Long studentId) {
		this.studentId = studentId;
	}

	public Long getRefId() {
		return refId;
	}

	public void setRefId(Long refId) {
		this.refId = refId;
	}

	public String getFileName() {
		return fileName;
	}

	public void setFileName(String fileName) {
		this.fileName = fileName;
	}

	@Enumerated(EnumType.STRING)
	public EnumFileType getFileType() {
		return fileType;
	}

	public void setFileType(EnumFileType fileType) {
		this.fileType = fileType;
	}

	public Date getDateCreated() {
		return dateCreated;
	}

	public void setDateCreated(Date dateCreated) {
		this.dateCreated = dateCreated;
	}

	public void setSNeedId(Long sNeedId) {
		this.sNeedId = sNeedId;
	}

	public Long getSNeedId() {
		return sNeedId;
	}

	public void setVehicleId(Long vehicleId) {
		this.vehicleId = vehicleId;
	}

	public Long getVehicleId() {
		return vehicleId;
	}

	public void setContentType(String contentType) {
		this.contentType = contentType;
	}

	public String getContentType() {
		return contentType;
	}

	public void setBlobFileData(BlobFileData blobFileData) {
		this.blobFileData = blobFileData;
	}

	@OneToOne(cascade = CascadeType.ALL, fetch = FetchType.LAZY)
	@JoinColumn(name = "blobid")
	public BlobFileData getBlobFileData() {
		return blobFileData;
	}

}
