package com.itelasoft.pso.beans;

import javax.persistence.CascadeType;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.OneToOne;
import javax.persistence.Table;
import javax.persistence.Transient;

import org.hibernate.search.annotations.Analyze;
import org.hibernate.search.annotations.Field;
import org.hibernate.search.annotations.Index;
import org.hibernate.search.annotations.Indexed;
import org.hibernate.search.annotations.Store;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : pso
//  @ Author : Tharindu
//
//

@Entity
@Indexed
@Table(name = "locations")
public class Location extends BaseEntity {
	private Long id;
	@Field(index = Index.YES, analyze = Analyze.YES, store = Store.NO)
	private String name;
	@Field(index = Index.YES, analyze = Analyze.YES, store = Store.NO)
	private String locationCode;
	private Contact contact;
	private ProgramEvent latestEvent;
	private boolean active;
	private boolean criminalCheck;

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	public Long getId() {
		return id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@OneToOne(cascade = CascadeType.ALL)
	@JoinColumn(name = "contactId")
	public Contact getContact() {
		return contact;
	}

	public void setContact(Contact contact) {
		this.contact = contact;
	}

	public void setLocationCode(String locationCode) {
		this.locationCode = locationCode;
	}

	public String getLocationCode() {
		return locationCode;
	}

	public void setLatestEvent(ProgramEvent latestEvent) {
		this.latestEvent = latestEvent;
	}

	@Transient
	public ProgramEvent getLatestEvent() {
		return latestEvent;
	}

	public void setActive(boolean active) {
		this.active = active;
	}

	@Transient
	public boolean isActive() {
		return active;
	}

	public boolean isCriminalCheck() {
		return criminalCheck;
	}

	public void setCriminalCheck(boolean criminalCheck) {
		this.criminalCheck = criminalCheck;
	}

}
